//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCover.SMSGataway.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsReceipt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SmsReceipt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SmsReceiptIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.DateTime DateDeliveredField;
        
        private int SmsReceiptDownloadIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SmsReceiptID {
            get {
                return this.SmsReceiptIDField;
            }
            set {
                if ((this.SmsReceiptIDField.Equals(value) != true)) {
                    this.SmsReceiptIDField = value;
                    this.RaisePropertyChanged("SmsReceiptID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateDelivered {
            get {
                return this.DateDeliveredField;
            }
            set {
                if ((this.DateDeliveredField.Equals(value) != true)) {
                    this.DateDeliveredField = value;
                    this.RaisePropertyChanged("DateDelivered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SmsReceiptDownloadID {
            get {
                return this.SmsReceiptDownloadIDField;
            }
            set {
                if ((this.SmsReceiptDownloadIDField.Equals(value) != true)) {
                    this.SmsReceiptDownloadIDField = value;
                    this.RaisePropertyChanged("SmsReceiptDownloadID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.downloaderSoap")]
    public interface downloaderSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        RoadCover.SMSGataway.ServiceReference1.HelloWorldResponse HelloWorld(RoadCover.SMSGataway.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<RoadCover.SMSGataway.ServiceReference1.HelloWorldResponse> HelloWorldAsync(RoadCover.SMSGataway.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetSmsReceiptsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsReceipts", ReplyAction="*")]
        RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsResponse GetSmsReceipts(RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsReceipts", ReplyAction="*")]
        System.Threading.Tasks.Task<RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsResponse> GetSmsReceiptsAsync(RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public RoadCover.SMSGataway.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(RoadCover.SMSGataway.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public RoadCover.SMSGataway.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(RoadCover.SMSGataway.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsReceiptsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsReceipts", Namespace="http://tempuri.org/", Order=0)]
        public RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequestBody Body;
        
        public GetSmsReceiptsRequest() {
        }
        
        public GetSmsReceiptsRequest(RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSmsReceiptsRequestBody {
        
        public GetSmsReceiptsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsReceiptsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsReceiptsResponse", Namespace="http://tempuri.org/", Order=0)]
        public RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsResponseBody Body;
        
        public GetSmsReceiptsResponse() {
        }
        
        public GetSmsReceiptsResponse(RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsReceiptsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RoadCover.SMSGataway.ServiceReference1.SmsReceipt[] GetSmsReceiptsResult;
        
        public GetSmsReceiptsResponseBody() {
        }
        
        public GetSmsReceiptsResponseBody(RoadCover.SMSGataway.ServiceReference1.SmsReceipt[] GetSmsReceiptsResult) {
            this.GetSmsReceiptsResult = GetSmsReceiptsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface downloaderSoapChannel : RoadCover.SMSGataway.ServiceReference1.downloaderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class downloaderSoapClient : System.ServiceModel.ClientBase<RoadCover.SMSGataway.ServiceReference1.downloaderSoap>, RoadCover.SMSGataway.ServiceReference1.downloaderSoap {
        
        public downloaderSoapClient() {
        }
        
        public downloaderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public downloaderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public downloaderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public downloaderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RoadCover.SMSGataway.ServiceReference1.HelloWorldResponse RoadCover.SMSGataway.ServiceReference1.downloaderSoap.HelloWorld(RoadCover.SMSGataway.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            RoadCover.SMSGataway.ServiceReference1.HelloWorldRequest inValue = new RoadCover.SMSGataway.ServiceReference1.HelloWorldRequest();
            inValue.Body = new RoadCover.SMSGataway.ServiceReference1.HelloWorldRequestBody();
            RoadCover.SMSGataway.ServiceReference1.HelloWorldResponse retVal = ((RoadCover.SMSGataway.ServiceReference1.downloaderSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RoadCover.SMSGataway.ServiceReference1.HelloWorldResponse> RoadCover.SMSGataway.ServiceReference1.downloaderSoap.HelloWorldAsync(RoadCover.SMSGataway.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<RoadCover.SMSGataway.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            RoadCover.SMSGataway.ServiceReference1.HelloWorldRequest inValue = new RoadCover.SMSGataway.ServiceReference1.HelloWorldRequest();
            inValue.Body = new RoadCover.SMSGataway.ServiceReference1.HelloWorldRequestBody();
            return ((RoadCover.SMSGataway.ServiceReference1.downloaderSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsResponse RoadCover.SMSGataway.ServiceReference1.downloaderSoap.GetSmsReceipts(RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequest request) {
            return base.Channel.GetSmsReceipts(request);
        }
        
        public RoadCover.SMSGataway.ServiceReference1.SmsReceipt[] GetSmsReceipts() {
            RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequest inValue = new RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequest();
            inValue.Body = new RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequestBody();
            RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsResponse retVal = ((RoadCover.SMSGataway.ServiceReference1.downloaderSoap)(this)).GetSmsReceipts(inValue);
            return retVal.Body.GetSmsReceiptsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsResponse> RoadCover.SMSGataway.ServiceReference1.downloaderSoap.GetSmsReceiptsAsync(RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequest request) {
            return base.Channel.GetSmsReceiptsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsResponse> GetSmsReceiptsAsync() {
            RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequest inValue = new RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequest();
            inValue.Body = new RoadCover.SMSGataway.ServiceReference1.GetSmsReceiptsRequestBody();
            return ((RoadCover.SMSGataway.ServiceReference1.downloaderSoap)(this)).GetSmsReceiptsAsync(inValue);
        }
    }
}
